version: "3"

services:
    web:
        hostname: web
        build:
            context: ./backend
            dockerfile: ./config/backend/Dockerfile
        container_name: backend
        command: >
            bash -c "
                python manage.py collectstatic --no-input &&
                python manage.py migrate --no-input &&
                gunicorn fjob.wsgi:application -w 4 -b 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - redis
            - celery
        env_file:
            - .env
        restart: always

    redis:
        image: redis:latest
        container_name: fjob-redis-dev
        ports:
            - "6379:6379"
        restart: always

    celery:
        build:
            context: ./backend/core
            dockerfile: ./config/backend/Dockerfile
        container_name: celery
        command: celery -A core.celery worker -l info
        volumes:
            - .:/app/
        depends_on:
            - redis
        restart: always
