# Generated by Django 5.0.1 on 2024-02-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='openai_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
