# Generated by Django 5.0.1 on 2024-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_scenario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_storage',
            field=models.FloatField(default=0),
        ),
    ]
