# Generated by Django 5.0.1 on 2024-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_alter_project_current_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='limit_storage',
            field=models.FloatField(default=0),
        ),
    ]
