# Generated by Django 5.0.1 on 2024-02-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ManyToManyField(to='subscription.productprice'),
        ),
    ]
